- hosts: namenode
  sudo: Yes
  vars:
        network: eth1
  
  tasks:
        - name: Test
          template: src=../templates/{{item}}.j2 dest=/home/hadoop/horton_install/dummy 
          with_items:
                - hosts
