# This playbook install mysql server (http://www.mysql.com/).
# Based on a playbook by https://github.com/fourkitchens/server-playbooks

- name: MySQL | Install MySQL and related packages
  yum: name={{ item }} state=installed
  with_items:
        - mysql
        - mysql-server
        - MySQL-python
        - mysql-connector-java
  register: mysql_installed

- name: MySQL | Start mysql
  service: name=mysqld state=started

#When run for the first time, we need to remove the login_user and login_password as root will not have a password set.
- name: MySQL | update mysql root password for all root accounts
  mysql_user: name=root host=localhost password=$root_db_password login_user=root login_password=$root_db_password

- name: MySQL | Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} login_user=root login_password=$root_db_password password=${root_db_password}
  with_items:
        - $ansible_hostname
        - 127.0.0.1
        - ::1

#- name: MySQL | Ensure anonymous users are not in the database
#  mysql_user: name="" host=$item login_user=root login_password=$root_db_password state="absent"
#  with_items:
#        - localhost
#        - ${ansible_hostname}
#  ignore_errors: yes

#        - name: MySQL | Update MySQL root password for all root accounts
#          mysql_user: name=root host=localhost password=${root_db_password}

- name: MySQL | Remove the MySQL test database
  mysql_db: db=test login_user=root login_password=$root_db_password state=absent
  ignore_errors: yes
 
- name: MySQL | Create Hive user
  mysql_user: name=${HIVE_MYSQL_USER} host= password=${HIVE_MYSQL_PASSWD} login_user=root login_password=${root_db_password} priv=*.*:ALL 
  ignore_errors: yes

- name: MySQL | Create Hive DB
  mysql_db: db=${HIVE_DB} state=present login_user=${HIVE_MYSQL_USER} login_password=${HIVE_MYSQL_PASSWD} encoding="utf8"
  ignore_errors: yes
