- name: Hive | Copy stop script
  template: src={{item}}.j2 dest=${HIVE_CONF_DIR}/{{item}} owner=${HIVE_USER} group=${HADOOP_GROUP} mode=755
  with_items:
        - stopHiveMetastore.sh

- name: Stop Hive metastore
  shell: ${HIVE_CONF_DIR}/stopHiveMetastore.sh

