---
# Start MapReduce
# WARNING: NEED TO START HDFS first!

- name: Start Mapreduce on tasktrackers
  command: sudo -u ${MAPRED_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} start tasktracker

