- name: HDP | Configure Hortonworks yum repo
  get_url: url=${HADOOP_REPO} dest=/etc/yum.repos.d/hdp.repo force=no owner=root group=root

- name: HDP | Configure Ambari yum repo
  get_url: url=${AMBARI_REPO} dest=/etc/yum.repos.d/ambari.repo force=no owner=root group=root

- name: NAGIOS | install epel repo
  action: command chdir=/tmp wget http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

- name: NAGIOS | install epel
  action: command chdir=/tmp rpm --force -Uvh epel-release-6-8.noarch.rpm 
  ignore_errors: yes

- name: NAGIOS | Remove epel tmp rpm
  file: dest=/tmp/epel-release-6-8.noarch.rpm state=absent

- name: NAGIOS | Clean up in case this script is run more than once
  yum: name=nagios state=absent
  ignore_errors: yes

- name: NAGIOS | Installing packages on the server
  yum: name={{item}} state=installed
  with_items:
        - httpd
        - php
        - net-snmp
        - net-snmp-utils
        - php-pecl-json
        - net-snmp-perl
        - perl-Net-SNMP
        - fping
        - nagios
        - nagios-plugins
        - hdp_mon_nagios_addons
        - nrpe
        - nagios-plugins-all

- name: NAGIOS | Ensure apache is running
  action: service name=httpd state=started

- name: NAGIOS | copy objects
  copy: src={{item}} dest=/etc/nagios/objects/ owner=nagios mode=755
  with_fileglob: ../files/nagios_objects/* 

- name: NAGIOS | copy plugins
  copy: src={{item}} dest=/usr/lib64/nagios/plugins owner=nagios mode=755
  with_fileglob: ../files/nagios_plugins/*

- name: NAGIOS | set Nagios Admin pass
  command: htpasswd -c -b /etc/nagios/htpasswd.users ${NAGIOS_USER} ${NAGIOS_PASS}

- name: NAGIOS | New command
  template: src=../templates/{{item}}.j2 dest=/tmp/{{item}} mode=755
  with_items:
        - insert_new_cmd.sh

- name: NAGIOS | Set up Nagios new cmd
  command: sh /tmp/insert_new_cmd.sh

- name: NAGIOS | Remove tmp file
  command: rm -rf /tmp/insert_new_cmd.sh

- name: NAGIOS | Copy rest of the configurations
  copy: src=../templates/nagios/{{item}}.j2 dest=/etc/nagios/objects/{{item}}
  with_items:
        - hadoop-commands.cfg
        - hadoop-services.cfg

- name: NAGIOS | Add config file
  lineinfile: dest=/etc/nagios/nagios.cfg regexp="^cfg_file=/etc/nagios/objects/hadoop-commands.cfg" line="cfg_file=/etc/nagios/objects/hadoop-commands.cfg"

- name: NAGIOS | Add config file
  lineinfile: dest=/etc/nagios/nagios.cfg regexp="^cfg_file=/etc/nagios/objects/hadoop-services.cfg" line="cfg_file=/etc/nagios/objects/hadoop-services.cfg"

- name: NAGIOS | Add config file
  lineinfile: dest=/etc/nagios/nagios.cfg regexp="^cfg_file=/etc/nagios/objects/hadoop-servicegroups.cfg" line="cfg_file=/etc/nagios/objects/hadoop-servicegroups.cfg"

- name: NAGIOS | Make sure nagios email is configured and hadoop config files are set
  lineinfile: dest=/etc/nagios/nagios.cfg regexp="^admin_email=" line="admin_email={{NAGIOS_EMAIL}}"
