- name: HDP | Create HDFS directories - DN
  file: path={{item}} state=absent
  with_items:
        - ${HDFS_LOG_DIR}
        - ${HDFS_PID_DIR}
  ignore_errors: yes

- name: HDP | Create HDFS directories - DN
  file: path={{item}} owner=${HDFS_USER} group=${HADOOP_GROUP} mode=755 state=directory
  with_items:
        - ${HDFS_LOG_DIR}
        - ${HDFS_PID_DIR}

- name: HDP | Delete HDFS directories - DN data dir - in case we are running this not for the first time
  file: path={{item}} state=absent
  with_items:
        - ${DFS_DATA_DIR}
  ignore_errors: yes

- name: HDP | Create HDFS directories - DN data dir
  file: path={{item}} owner=${HDFS_USER} group=${HADOOP_GROUP} mode=750 state=directory
  with_items:
        - ${DFS_DATA_DIR}
