- hosts: hiveMetastore
  sudo: Yes
  vars_files:
        - [ "../vars/userGrp.yml" ]
        - [ "../vars/dirsHDP.yml" ]

  tasks:
        - name: WebHCat | Start WehHCat
          command: sudo -u ${WEBHCAT_USER} /usr/lib/hcatalog/sbin/webhcat_server.sh start

