- name: HDP | Copy configuration files
  template: src=../templates/{{item}}.j2 dest=${HADOOP_CONF_DIR}/{{item}} owner=${HDFS_USER} group=${HADOOP_GROUP} mode=755
  with_items:
        - capacity-scheduler.xml
        - commons-logging.properties
        - core-site.xml
        - hadoop-env.sh
        - hadoop-metrics2.properties
        - hadoop-policy.xml
        - hdfs-site.xml
        - mapred-site.xml
        - mapreduce-queue-acls.xml
        - taskcontroller.cfg
        - health_check
